### PR TITLE
Added new strings

### PR DESCRIPTION
**Pull request by MaDill**
Is it possible to get a message before you release a new version to the play store? Maybe one week in advance. Could be nice, then the translators have the possibility to update their translation and the version in the store has the updated language files. The released one have some missing German strings.

### CODE REVIEW

**Comment by geometer** [comment]
Sorry. :) We release often, and usually we add strings on the last stage.

**Comment by geometer** [comment]
Thanks!

**Comment by geometer** [comment]
Btw, there is one more file to translate now: https://github.com/geometer/FBReaderJ/blob/master/assets/data/premium/en.html

Anyway, thank you for your participating this project!

**Comment by MaDill** [comment]
Can you create the de.html and commit it please. I translate it then later.

**Comment by geometer** [comment]
Done. https://github.com/geometer/FBReaderJ/blob/master/assets/data/premium/de.html

**Pull request merged**
